---

- name: Configure bearwall ruleset {{ item.name }}
  ansible.builtin.template:
    src: ruleset
    dest: "/etc/bearwall2/rulesets.d/{{ item.name }}.rule"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify: apply bearwall2
