---

- name: Configure bearwall interface {{ item.name }} as class {{ item.class }}
  ansible.builtin.file:
    src: "/etc/bearwall2/classes.d/{{ item.class }}"
    dest: "/etc/bearwall2/interfaces.d/{{ item.name }}.if"
    state: link
  when: "'class' in item"
  notify: apply bearwall2

- name: Configure bearwall interface {{ item.name }}
  ansible.builtin.template:
    src: if
    dest: "/etc/bearwall2/interfaces.d/{{ item.name }}.if"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  when: "'class' not in item"
  notify: apply bearwall2
